"""Paper trade portfolio tracker for the ROT platform.

Tracks paper trades generated by the ROT signal pipeline, computes win/loss
ratio and average P&L, identifies best and worst trades, exports the log to
CSV, and provides a summary dict suitable for the FastAPI dashboard.

Trades are persisted to a local JSON-lines file by default so no database
connection is required.  Use :meth:`PortfolioTracker.export_csv` to write
a standard CSV for analysis.

Typical usage::

    from rot.portfolio.tracker import PortfolioTracker, PaperTrade

    tracker = PortfolioTracker()

    # Record a new trade
    tracker.open_trade(
        trade_id="t001",
        ticker="AAPL",
        strategy="bull_call_spread",
        direction="bullish",
        entry_price=5.20,
        quantity=1,
        signal_confidence=0.82,
    )

    # Close it later with the exit price
    tracker.close_trade("t001", exit_price=9.50)

    # Print a summary
    tracker.print_summary()
"""

from __future__ import annotations

import csv
import json
import logging
import os
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

_DEFAULT_LOG_FILE = "rot_paper_trades.jsonl"


# ---------------------------------------------------------------------------
# Data structure
# ---------------------------------------------------------------------------


@dataclass
class PaperTrade:
    """A single paper options trade record.

    Attributes:
        trade_id: Unique identifier for the trade.
        ticker: Equity ticker symbol.
        strategy: Options strategy label (e.g. ``"bull_call_spread"``).
        direction: ``"bullish"`` or ``"bearish"``.
        entry_price: Entry premium per contract (USD).
        quantity: Number of contracts.
        signal_confidence: Confidence of the originating ROT signal [0, 1].
        opened_at: ISO timestamp when the trade was opened.
        exit_price: Exit premium per contract (USD) or ``None`` if open.
        closed_at: ISO timestamp when closed, or ``None`` if open.
        pnl: Realised P&L (USD) or ``None`` if still open.
        status: ``"open"`` or ``"closed"``.
        notes: Optional free-text notes.
    """

    trade_id: str
    ticker: str
    strategy: str
    direction: str
    entry_price: float
    quantity: int = 1
    signal_confidence: float = 0.0
    opened_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    exit_price: Optional[float] = None
    closed_at: Optional[str] = None
    pnl: Optional[float] = None
    status: str = "open"
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @property
    def cost_basis(self) -> float:
        """Total cost of the trade (entry price × quantity × 100 shares/contract)."""
        return self.entry_price * self.quantity * 100

    @property
    def pnl_pct(self) -> Optional[float]:
        """Percentage return on cost basis, or ``None`` if still open."""
        if self.pnl is None or self.cost_basis == 0:
            return None
        return self.pnl / self.cost_basis * 100


# ---------------------------------------------------------------------------
# Tracker
# ---------------------------------------------------------------------------


class PortfolioTracker:
    """Tracks ROT paper trades and computes portfolio analytics.

    Trades are persisted to a JSON-lines file.  On construction any existing
    log file is loaded so the tracker resumes across restarts.

    Args:
        log_file: Path to the JSONL persistence file.
        starting_balance: Virtual cash balance in USD.
    """

    def __init__(
        self,
        log_file: str = _DEFAULT_LOG_FILE,
        starting_balance: float = 100_000.0,
    ) -> None:
        self._log_file = log_file
        self._starting_balance = starting_balance
        self._trades: Dict[str, PaperTrade] = {}
        self._load()

    # ------------------------------------------------------------------
    # Trade lifecycle
    # ------------------------------------------------------------------

    def open_trade(
        self,
        trade_id: str,
        ticker: str,
        strategy: str,
        direction: str,
        entry_price: float,
        quantity: int = 1,
        signal_confidence: float = 0.0,
        notes: str = "",
    ) -> PaperTrade:
        """Record the opening of a paper trade.

        Args:
            trade_id: Unique identifier (caller-generated).
            ticker: Equity symbol.
            strategy: Options strategy label.
            direction: ``"bullish"`` or ``"bearish"``.
            entry_price: Entry premium per contract.
            quantity: Number of contracts.
            signal_confidence: Confidence of originating ROT signal.
            notes: Optional notes.

        Returns:
            The newly created :class:`PaperTrade`.

        Raises:
            ValueError: If a trade with the same *trade_id* already exists.
        """
        if trade_id in self._trades:
            raise ValueError(f"Trade '{trade_id}' already exists.")

        trade = PaperTrade(
            trade_id=trade_id,
            ticker=ticker,
            strategy=strategy,
            direction=direction,
            entry_price=entry_price,
            quantity=quantity,
            signal_confidence=signal_confidence,
            notes=notes,
        )
        self._trades[trade_id] = trade
        self._append_to_log(trade.to_dict())
        log.info("portfolio.open trade_id=%s ticker=%s entry=%.2f", trade_id, ticker, entry_price)
        return trade

    def close_trade(
        self,
        trade_id: str,
        exit_price: float,
        notes: str = "",
    ) -> PaperTrade:
        """Close an open paper trade and compute realised P&L.

        P&L = (exit_price - entry_price) × quantity × 100

        Args:
            trade_id: Identifier of the trade to close.
            exit_price: Exit premium per contract.
            notes: Optional additional notes.

        Returns:
            The updated :class:`PaperTrade`.

        Raises:
            KeyError: If *trade_id* is not found.
            ValueError: If the trade is already closed.
        """
        if trade_id not in self._trades:
            raise KeyError(f"Trade '{trade_id}' not found.")

        trade = self._trades[trade_id]
        if trade.status == "closed":
            raise ValueError(f"Trade '{trade_id}' is already closed.")

        trade.exit_price = exit_price
        trade.closed_at = datetime.now(timezone.utc).isoformat()
        trade.pnl = round((exit_price - trade.entry_price) * trade.quantity * 100, 2)
        trade.status = "closed"
        if notes:
            trade.notes = (trade.notes + " | " + notes).strip(" | ")

        self._append_to_log(trade.to_dict())
        log.info(
            "portfolio.close trade_id=%s ticker=%s pnl=%.2f",
            trade_id, trade.ticker, trade.pnl,
        )
        return trade

    # ------------------------------------------------------------------
    # Analytics
    # ------------------------------------------------------------------

    @property
    def open_trades(self) -> List[PaperTrade]:
        """All trades with status ``"open"``."""
        return [t for t in self._trades.values() if t.status == "open"]

    @property
    def closed_trades(self) -> List[PaperTrade]:
        """All trades with status ``"closed"``."""
        return [t for t in self._trades.values() if t.status == "closed"]

    def summary(self) -> Dict[str, Any]:
        """Compute and return a performance summary dictionary.

        Returns:
            Dict with keys: ``total_trades``, ``open_trades``,
            ``closed_trades``, ``wins``, ``losses``, ``win_rate``,
            ``total_pnl``, ``avg_pnl``, ``best_trade``, ``worst_trade``,
            ``starting_balance``, ``current_balance``.
        """
        closed = self.closed_trades
        if not closed:
            return {
                "total_trades": len(self._trades),
                "open_trades": len(self.open_trades),
                "closed_trades": 0,
                "wins": 0,
                "losses": 0,
                "win_rate": None,
                "total_pnl": 0.0,
                "avg_pnl": None,
                "best_trade": None,
                "worst_trade": None,
                "starting_balance": self._starting_balance,
                "current_balance": self._starting_balance,
            }

        pnls = [t.pnl for t in closed if t.pnl is not None]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]
        total_pnl = sum(pnls)
        avg_pnl = total_pnl / len(pnls) if pnls else 0.0
        win_rate = len(wins) / len(pnls) if pnls else 0.0

        best = max(closed, key=lambda t: t.pnl or float("-inf"))
        worst = min(closed, key=lambda t: t.pnl or float("inf"))

        return {
            "total_trades": len(self._trades),
            "open_trades": len(self.open_trades),
            "closed_trades": len(closed),
            "wins": len(wins),
            "losses": len(losses),
            "win_rate": round(win_rate, 4),
            "total_pnl": round(total_pnl, 2),
            "avg_pnl": round(avg_pnl, 2),
            "best_trade": {
                "trade_id": best.trade_id,
                "ticker": best.ticker,
                "pnl": best.pnl,
                "strategy": best.strategy,
            },
            "worst_trade": {
                "trade_id": worst.trade_id,
                "ticker": worst.ticker,
                "pnl": worst.pnl,
                "strategy": worst.strategy,
            },
            "starting_balance": self._starting_balance,
            "current_balance": round(self._starting_balance + total_pnl, 2),
        }

    def print_summary(self) -> None:
        """Print a human-readable performance summary to stdout."""
        s = self.summary()
        print("\n" + "=" * 60)
        print("  ROT Portfolio Tracker — Paper Trade Summary")
        print("=" * 60)
        print(f"  Total Trades   : {s['total_trades']}")
        print(f"  Open / Closed  : {s['open_trades']} / {s['closed_trades']}")
        if s["win_rate"] is not None:
            print(f"  Win Rate       : {s['win_rate'] * 100:.1f}%  ({s['wins']}W / {s['losses']}L)")
        print(f"  Total P&L      : ${s['total_pnl']:,.2f}")
        if s["avg_pnl"] is not None:
            print(f"  Avg P&L/Trade  : ${s['avg_pnl']:,.2f}")
        if s["best_trade"]:
            b = s["best_trade"]
            print(f"  Best Trade     : {b['ticker']} {b['strategy']}  ${b['pnl']:,.2f}")
        if s["worst_trade"]:
            w = s["worst_trade"]
            print(f"  Worst Trade    : {w['ticker']} {w['strategy']}  ${w['pnl']:,.2f}")
        print(f"  Starting $     : ${s['starting_balance']:,.2f}")
        print(f"  Current $      : ${s['current_balance']:,.2f}")
        print("=" * 60 + "\n")

    def all_trades_list(self) -> List[Dict[str, Any]]:
        """Return all trades as a list of dicts (open and closed)."""
        return [t.to_dict() for t in self._trades.values()]

    # ------------------------------------------------------------------
    # Export
    # ------------------------------------------------------------------

    def export_csv(self, output_path: str = "rot_paper_trades.csv") -> str:
        """Export all trades to a CSV file.

        Args:
            output_path: Destination CSV path.

        Returns:
            Absolute path to the written CSV file.
        """
        trades = self.all_trades_list()
        if not trades:
            log.warning("portfolio.export_csv no_trades")
            return output_path

        fieldnames = list(trades[0].keys())
        with open(output_path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(trades)

        abs_path = os.path.abspath(output_path)
        log.info("portfolio.exported path=%s rows=%d", abs_path, len(trades))
        return abs_path

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _append_to_log(self, record: Dict[str, Any]) -> None:
        """Append a trade record to the JSONL persistence file."""
        try:
            with open(self._log_file, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(record) + "\n")
        except OSError as exc:
            log.error("portfolio.log_write_failed error=%s", exc)

    def _load(self) -> None:
        """Load existing trades from the JSONL file on startup."""
        if not os.path.exists(self._log_file):
            return
        try:
            with open(self._log_file, encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        trade = PaperTrade(**{k: data[k] for k in PaperTrade.__dataclass_fields__ if k in data})
                        # Most-recent record for each trade_id wins
                        self._trades[trade.trade_id] = trade
                    except Exception as exc:
                        log.debug("portfolio.load_line_skip error=%s", exc)
            log.info("portfolio.loaded trades=%d file=%s", len(self._trades), self._log_file)
        except OSError as exc:
            log.warning("portfolio.load_failed error=%s", exc)
