"""TradingView Pine Script generator.

Converts ROT signals into Pine Script v5 indicators and strategies.
Since Pine Script doesn't support external data fetching, signals are
hardcoded into arrays that users must periodically regenerate.
"""

from __future__ import annotations

import datetime
import logging
from typing import List

from .types import PineScriptConfig, ScriptType, TVSignalOverlay

log = logging.getLogger(__name__)


class PineScriptGenerator:
    """Generate Pine Script v5 code from ROT signals.

    Provides five script types:
    1. signal_overlay - Plot signals as chart markers
    2. confidence_heatmap - Color-coded confidence gradient
    3. watchlist_indicator - Multi-ticker panel
    4. strategy_backtest - Full strategy with entry/exit logic
    5. alert_conditions - Alert conditions based on criteria
    """

    def __init__(self, config: PineScriptConfig):
        """Initialize generator with configuration.

        Args:
            config: PineScriptConfig with filtering and display options
        """
        self.config = config
        config.validate()  # Validate on init

    def generate(
        self,
        signals: List[TVSignalOverlay],
        script_type: ScriptType = "signal_overlay",
    ) -> str:
        """Generate Pine Script based on type.

        Args:
            signals: List of TVSignalOverlay objects to include
            script_type: Type of script to generate

        Returns:
            Complete Pine Script v5 code as string

        Raises:
            ValueError: If script_type is invalid or signals list is malformed
        """
        if script_type == "signal_overlay":
            return self.generate_signal_overlay(signals)
        elif script_type == "confidence_heatmap":
            return self.generate_confidence_heatmap(signals)
        elif script_type == "watchlist_indicator":
            return self.generate_watchlist_indicator(signals)
        elif script_type == "strategy_backtest":
            return self.generate_strategy_backtest(signals)
        elif script_type == "alert_conditions":
            return self.generate_alert_conditions(signals)
        else:
            raise ValueError(f"Invalid script_type: {script_type}")

    def generate_signal_overlay(self, signals: List[TVSignalOverlay]) -> str:
        """Generate indicator that plots signals as chart overlays.

        Creates plotshape() markers at signal timestamps with labels.
        Bullish signals plot below candle, bearish above.

        Args:
            signals: List of signals to plot

        Returns:
            Pine Script v5 indicator code
        """
        script_lines = [
            "//@version=5",
            f'indicator("{self.config.script_name}", overlay=true)',
            "",
            "// Generated by ROT (Reddit Options Trader)",
            f"// Generated at: {datetime.datetime.utcnow().isoformat()}Z",
            f"// Signals: {len(signals)}",
            f"// Min confidence: {self.config.min_confidence}",
            "",
        ]

        if not signals:
            script_lines.extend([
                "// No signals match criteria",
                'label.new(bar_index, high, "No ROT signals", color=color.gray, textcolor=color.white)',
            ])
            return "\n".join(script_lines)

        # Convert signals to arrays
        signal_data = [s.to_pine_arrays() for s in signals]

        # Build timestamp and stance arrays
        timestamps = [str(s["ts"]) for s in signal_data]
        stances = [str(s["stance_code"]) for s in signal_data]
        confidences = [f"{s['conf']:.4f}" for s in signal_data]

        script_lines.extend([
            "// Signal data arrays (hardcoded - regenerate periodically)",
            f"var signal_times = array.from({', '.join(timestamps)})",
            f"var signal_stances = array.from({', '.join(stances)})",
            f"var signal_confidences = array.from({', '.join(confidences)})",
            "",
            "// Check if current bar matches a signal",
            "signal_index = -1",
            "current_time = time / 1000  // Convert to Unix seconds",
            "",
            "for i = 0 to array.size(signal_times) - 1",
            "    if math.abs(current_time - array.get(signal_times, i)) < 60  // Within 1 minute",
            "        signal_index := i",
            "        break",
            "",
        ])

        # Add plotting logic
        script_lines.extend([
            "// Plot signal markers",
            "is_bullish = signal_index >= 0 and array.get(signal_stances, signal_index) > 0",
            "is_bearish = signal_index >= 0 and array.get(signal_stances, signal_index) < 0",
            "",
        ])

        if self.config.show_confidence_color:
            script_lines.extend([
                "// Confidence-based coloring",
                "signal_conf = signal_index >= 0 ? array.get(signal_confidences, signal_index) : 0.0",
                "bull_color = signal_conf > 0.7 ? color.new(color.green, 0) : signal_conf > 0.5 ? color.new(color.green, 30) : color.new(color.green, 60)",
                "bear_color = signal_conf > 0.7 ? color.new(color.red, 0) : signal_conf > 0.5 ? color.new(color.red, 30) : color.new(color.red, 60)",
                "",
            ])
        else:
            script_lines.extend([
                "bull_color = color.green",
                "bear_color = color.red",
                "",
            ])

        script_lines.extend([
            "plotshape(is_bullish, style=shape.triangleup, location=location.belowbar, color=bull_color, size=size.small, title='Bullish Signal')",
            "plotshape(is_bearish, style=shape.triangledown, location=location.abovebar, color=bear_color, size=size.small, title='Bearish Signal')",
            "",
        ])

        if self.config.show_labels:
            # Build label text array
            labels = [f'"{s["label"]}"' for s in signal_data]
            script_lines.extend([
                f"var signal_labels = array.from({', '.join(labels)})",
                "",
                "// Add text labels",
                "if signal_index >= 0",
                "    label_text = array.get(signal_labels, signal_index)",
                "    label_y = is_bullish ? low : high",
                "    label_style = is_bullish ? label.style_label_up : label.style_label_down",
                "    label.new(bar_index, label_y, label_text, style=label_style, color=is_bullish ? bull_color : bear_color, textcolor=color.white)",
            ])

        if self.config.show_lines:
            script_lines.extend([
                "",
                "// Vertical line at signal",
                "line_color = is_bullish ? bull_color : bear_color",
                "if signal_index >= 0",
                "    line.new(bar_index, low, bar_index, high, color=line_color, width=1, style=line.style_dashed)",
            ])

        return "\n".join(script_lines)

    def generate_confidence_heatmap(self, signals: List[TVSignalOverlay]) -> str:
        """Generate indicator showing confidence as background color heatmap.

        Colors chart background based on most recent signal confidence:
        - Green gradient for bullish (darker = higher confidence)
        - Red gradient for bearish (darker = higher confidence)
        - Gray for mixed/unknown

        Args:
            signals: List of signals for heatmap

        Returns:
            Pine Script v5 indicator code
        """
        script_lines = [
            "//@version=5",
            f'indicator("{self.config.script_name} - Confidence Heatmap", overlay=true)',
            "",
            "// Confidence heatmap: background color shows signal strength",
            f"// Generated at: {datetime.datetime.utcnow().isoformat()}Z",
            f"// Signals: {len(signals)}",
            "",
        ]

        if not signals:
            script_lines.extend([
                "bgcolor(color.new(color.gray, 90), title='No signals')",
            ])
            return "\n".join(script_lines)

        # Sort signals by timestamp for forward-fill logic
        sorted_signals = sorted(signals, key=lambda s: s.timestamp)
        signal_data = [s.to_pine_arrays() for s in sorted_signals]

        timestamps = [str(s["ts"]) for s in signal_data]
        stances = [str(s["stance_code"]) for s in signal_data]
        confidences = [f"{s['conf']:.4f}" for s in signal_data]

        script_lines.extend([
            f"var signal_times = array.from({', '.join(timestamps)})",
            f"var signal_stances = array.from({', '.join(stances)})",
            f"var signal_confidences = array.from({', '.join(confidences)})",
            "",
            "// Find most recent signal (forward-fill)",
            "current_time = time / 1000",
            "recent_stance = 0",
            "recent_conf = 0.0",
            "",
            "for i = 0 to array.size(signal_times) - 1",
            "    if array.get(signal_times, i) <= current_time",
            "        recent_stance := array.get(signal_stances, i)",
            "        recent_conf := array.get(signal_confidences, i)",
            "",
            "// Calculate background color based on stance and confidence",
            "transparency = 90 - int(recent_conf * 60)  // Higher confidence = less transparent",
            "bg_color = recent_stance > 0 ? color.new(color.green, transparency) : recent_stance < 0 ? color.new(color.red, transparency) : color.new(color.gray, 95)",
            "",
            "bgcolor(bg_color, title='Confidence Heatmap')",
            "",
            "// Optional: plot confidence line",
            f"plot(recent_conf, title='Confidence', color=color.blue, linewidth=2)",
            f"hline(0.5, 'Threshold', color=color.gray, linestyle=hline.style_dashed)",
        ])

        return "\n".join(script_lines)

    def generate_watchlist_indicator(self, signals: List[TVSignalOverlay]) -> str:
        """Generate multi-ticker watchlist panel indicator.

        Creates a table showing recent signals across multiple tickers.
        Useful for monitoring a portfolio of ROT signals.

        Args:
            signals: List of signals (can be multi-ticker)

        Returns:
            Pine Script v5 indicator code with table display
        """
        script_lines = [
            "//@version=5",
            f'indicator("{self.config.script_name} - Watchlist", overlay=true)',
            "",
            "// Multi-ticker watchlist panel",
            f"// Generated at: {datetime.datetime.utcnow().isoformat()}Z",
            f"// Signals: {len(signals)}",
            "",
        ]

        if not signals:
            script_lines.extend([
                "var table t = table.new(position.top_right, 1, 1)",
                "if barstate.islast",
                '    table.cell(t, 0, 0, "No ROT signals", bgcolor=color.gray, text_color=color.white)',
            ])
            return "\n".join(script_lines)

        # Group signals by ticker, keep most recent per ticker
        ticker_signals = {}
        for sig in signals:
            if sig.ticker not in ticker_signals or sig.timestamp > ticker_signals[sig.ticker].timestamp:
                ticker_signals[sig.ticker] = sig

        # Sort by confidence descending
        sorted_tickers = sorted(
            ticker_signals.items(),
            key=lambda x: x[1].confidence,
            reverse=True,
        )[:10]  # Limit to 10 tickers for display

        script_lines.extend([
            f"// Top {len(sorted_tickers)} tickers by confidence",
            f"var table watchlist = table.new(position.top_right, 3, {len(sorted_tickers) + 1})",
            "",
            "if barstate.islast",
            "    // Header row",
            '    table.cell(watchlist, 0, 0, "Ticker", bgcolor=color.gray, text_color=color.white)',
            '    table.cell(watchlist, 1, 0, "Stance", bgcolor=color.gray, text_color=color.white)',
            '    table.cell(watchlist, 2, 0, "Conf", bgcolor=color.gray, text_color=color.white)',
            "",
        ])

        # Add rows for each ticker
        for idx, (ticker, sig) in enumerate(sorted_tickers, start=1):
            stance_text = "BULL" if sig.stance == "bullish" else "BEAR" if sig.stance == "bearish" else "MIX"
            stance_color = "color.green" if sig.stance == "bullish" else "color.red" if sig.stance == "bearish" else "color.orange"

            script_lines.extend([
                f'    table.cell(watchlist, 0, {idx}, "{ticker}", bgcolor=color.new(color.blue, 80), text_color=color.white)',
                f'    table.cell(watchlist, 1, {idx}, "{stance_text}", bgcolor={stance_color}, text_color=color.white)',
                f'    table.cell(watchlist, 2, {idx}, "{sig.confidence:.2f}", bgcolor=color.new(color.gray, 80), text_color=color.white)',
            ])

        return "\n".join(script_lines)

    def generate_strategy_backtest(self, signals: List[TVSignalOverlay]) -> str:
        """Generate full strategy with entry/exit logic for backtesting.

        Creates a strategy that:
        - Enters long on bullish signals (confidence >= min)
        - Enters short on bearish signals (confidence >= min)
        - Exits after next opposite signal or N bars

        Args:
            signals: List of signals to trade

        Returns:
            Pine Script v5 strategy code
        """
        script_lines = [
            "//@version=5",
            f'strategy("{self.config.script_name} Strategy", overlay=true, initial_capital={self.config.strategy_capital}, commission_type=strategy.commission.percent, commission_value={self.config.strategy_commission}, slippage={self.config.strategy_slippage})',
            "",
            "// Automated strategy based on ROT signals",
            f"// Generated at: {datetime.datetime.utcnow().isoformat()}Z",
            f"// Signals: {len(signals)}",
            f"// Min confidence: {self.config.min_confidence}",
            "",
        ]

        if not signals:
            script_lines.extend([
                "// No signals - strategy inactive",
            ])
            return "\n".join(script_lines)

        signal_data = [s.to_pine_arrays() for s in signals]
        timestamps = [str(s["ts"]) for s in signal_data]
        stances = [str(s["stance_code"]) for s in signal_data]
        confidences = [f"{s['conf']:.4f}" for s in signal_data]

        script_lines.extend([
            f"var signal_times = array.from({', '.join(timestamps)})",
            f"var signal_stances = array.from({', '.join(stances)})",
            f"var signal_confidences = array.from({', '.join(confidences)})",
            "",
            "// Find signal at current bar",
            "current_time = time / 1000",
            "signal_index = -1",
            "",
            "for i = 0 to array.size(signal_times) - 1",
            "    if math.abs(current_time - array.get(signal_times, i)) < 60",
            "        signal_index := i",
            "        break",
            "",
            "// Entry logic",
            "if signal_index >= 0",
            "    stance = array.get(signal_stances, signal_index)",
            "    conf = array.get(signal_confidences, signal_index)",
            "",
            f"    // Only trade signals above min confidence ({self.config.min_confidence})",
            f"    if conf >= {self.config.min_confidence}",
            "        if stance > 0  // Bullish",
            '            strategy.entry("Long", strategy.long, comment="ROT Bull")',
            '            strategy.close("Short")  // Close any short position',
            "",
            "        if stance < 0  // Bearish",
            '            strategy.entry("Short", strategy.short, comment="ROT Bear")',
            '            strategy.close("Long")  // Close any long position',
            "",
            "// Optional: Exit after 10 bars (adjust as needed)",
            "// strategy.exit('Exit Long', 'Long', loss=10, profit=20)",
            "// strategy.exit('Exit Short', 'Short', loss=10, profit=20)",
        ])

        return "\n".join(script_lines)

    def generate_alert_conditions(self, signals: List[TVSignalOverlay]) -> str:
        """Generate indicator with alert conditions.

        Creates alertcondition() statements that trigger when:
        - New bullish signal with confidence >= threshold
        - New bearish signal with confidence >= threshold

        Users can then configure TradingView alerts pointing to these conditions.

        Args:
            signals: List of signals to monitor

        Returns:
            Pine Script v5 indicator code with alert conditions
        """
        script_lines = [
            "//@version=5",
            f'indicator("{self.config.script_name} - Alerts", overlay=true)',
            "",
            "// Alert conditions for ROT signals",
            f"// Generated at: {datetime.datetime.utcnow().isoformat()}Z",
            f"// Alert threshold: {self.config.alert_min_confidence}",
            "",
        ]

        if not signals:
            script_lines.extend([
                "// No signals - alerts inactive",
            ])
            return "\n".join(script_lines)

        signal_data = [s.to_pine_arrays() for s in signals]
        timestamps = [str(s["ts"]) for s in signal_data]
        stances = [str(s["stance_code"]) for s in signal_data]
        confidences = [f"{s['conf']:.4f}" for s in signal_data]

        script_lines.extend([
            f"var signal_times = array.from({', '.join(timestamps)})",
            f"var signal_stances = array.from({', '.join(stances)})",
            f"var signal_confidences = array.from({', '.join(confidences)})",
            "",
            "// Check current bar for signal",
            "current_time = time / 1000",
            "signal_index = -1",
            "",
            "for i = 0 to array.size(signal_times) - 1",
            "    if math.abs(current_time - array.get(signal_times, i)) < 60",
            "        signal_index := i",
            "        break",
            "",
            "// Alert trigger conditions",
            "stance = signal_index >= 0 ? array.get(signal_stances, signal_index) : 0",
            "conf = signal_index >= 0 ? array.get(signal_confidences, signal_index) : 0.0",
            "",
            f"bullish_alert = stance > 0 and conf >= {self.config.alert_min_confidence}",
            f"bearish_alert = stance < 0 and conf >= {self.config.alert_min_confidence}",
            "",
        ])

        if self.config.alert_on_bullish:
            script_lines.append('alertcondition(bullish_alert, title="ROT Bullish Signal", message="ROT bullish signal detected")')

        if self.config.alert_on_bearish:
            script_lines.append('alertcondition(bearish_alert, title="ROT Bearish Signal", message="ROT bearish signal detected")')

        script_lines.extend([
            "",
            "// Visual indicators",
            "plotshape(bullish_alert, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.normal, title='Bullish Alert')",
            "plotshape(bearish_alert, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.normal, title='Bearish Alert')",
        ])

        return "\n".join(script_lines)

    @staticmethod
    def validate_pine_script(script: str) -> tuple[bool, str]:
        """Basic syntax validation for generated Pine Script.

        Checks for common syntax errors:
        - Unmatched brackets/parentheses
        - Unmatched quotes
        - Missing version declaration

        Args:
            script: Pine Script code to validate

        Returns:
            Tuple of (is_valid, error_message)
            If valid, error_message is empty string
        """
        lines = script.split("\n")

        # Check for version declaration
        if not any(line.strip().startswith("//@version=") for line in lines[:5]):
            return False, "Missing //@version= declaration in first 5 lines"

        # Check bracket/parenthesis matching
        bracket_stack = []
        paren_stack = []

        for line_num, line in enumerate(lines, start=1):
            # Skip comments
            if line.strip().startswith("//"):
                continue

            for char in line:
                if char == "[":
                    bracket_stack.append(line_num)
                elif char == "]":
                    if not bracket_stack:
                        return False, f"Unmatched ] at line {line_num}"
                    bracket_stack.pop()
                elif char == "(":
                    paren_stack.append(line_num)
                elif char == ")":
                    if not paren_stack:
                        return False, f"Unmatched ) at line {line_num}"
                    paren_stack.pop()

        if bracket_stack:
            return False, f"Unmatched [ at line {bracket_stack[-1]}"
        if paren_stack:
            return False, f"Unmatched ( at line {paren_stack[-1]}"

        # Check quote matching (simple check)
        for line_num, line in enumerate(lines, start=1):
            if line.strip().startswith("//"):
                continue

            # Count quotes (must be even)
            double_quotes = line.count('"')
            single_quotes = line.count("'")

            if double_quotes % 2 != 0:
                return False, f'Unmatched " at line {line_num}'
            if single_quotes % 2 != 0:
                return False, f"Unmatched ' at line {line_num}"

        return True, ""
